textured_strands: {
      "path_to_mesh": "MESH_PATH",
      "decoder_checkpoint_path": "./load/strandhead/strand_ckpt.pth",
      "num_strands": 1900,
      "max_num_strands": 100000,
      "texture_size": 256,
      "geometry_descriptor_size": 64,
      "appearance_descriptor_size": 16,
      "scalp_vertex_idx_path": "./load/flame_models/flame/NHC_scalp_vertex_idx.pth",
      "scalp_faces_path": "./load/flame_models/flame/NHC_scalp_faces.pth",
      "scalp_uvcoords_path": "./load/flame_models/flame/NHC_scalp_uvcoords.pth"
  }

diffusion_prior: {
      "use_diffusion": true,
      "start_denoise": 1,
      "diffuse_mask": "",
      "diffuse_bs": 32,
      "dif_path": "",  
       model: {
          "type": "image_v1",
          "input_channels": 64,
          "input_size": [32, 32],
          "patch_size": 1,
          "mapping_out": 256,
          "depths": [2, 4, 4],
          "channels": [128, 256, 512],
          "mapping_cond_dim": 0,
          "unet_cond_dim": 0,
          "cross_cond_dim": 0,
          "cross_attn_depths": None,
          "self_attn_depths": [false, false, false],
          "has_variance": true,
          "dropout_rate": 0.05,
          "skip_stages": 0,
          "augment_wrapper": false,
          "augment_prob": 0.12,
          "sigma_data": 0.5,
          "sigma_min": 0.02,
          "sigma_max": 40,
          "sigma_sample_density": {
              "type": "lognormal",
                "mean": -1.2,
                "std": 1.2
            }
      }
  }

render: {
    "use_render": true,
    "image_size": 512,
    "feat_size": 16,
    "mesh_path": "",
    "num_strands": 1900,
    "strands_len": 99,
    "logging_freq": 500,
    "out_channels": 3,
    "use_orients_cond": true,
    "use_silh": true,
 }
  
loss_factors: {
    "volume": 1.,
    "orient": 0.01,
    "chamfer": 1.,
    "raster_silh": 0.00001,
    "raster_l1": 0.001,
    "raster_alpha": 0.0,
    "L_diff": 0.001,
  }

general: {
    "lr": 0.001,
    "starting_rendering_iter": 1,
    "gamma": 0.5,
    "milestones": [1000, 2000, 3000], 
  }