name: "strand-texture-coarse"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-strand-datamodule"
data:
  batch_size: 1
  width: 512
  height: 512
  camera_distance_range: [3, 3]
  fovy_range: [40, 45]
  elevation_range: [-5, 45]
  azimuth_range: [-180, 180]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  eval_camera_distance: 3
  eval_fovy_deg: 45.
  eval_elevation_deg: 5.
  n_val_views: 120
  n_test_views: 120
  random_test: true
  test_part_ratio: [1.0, 0.0, 0.0, 0.0]
  sampling_type: "head_only"
  fullbody_part_ratio:
    step: [0]
    ratio: [[1.0, 0.0, 0.0, 0.0]]
  # full\head\upper body\lower body
  sim_flag: true
  RD_prob: 0.5

  multiview_RD_flag: true
  multiview_RD:
    batch_size: 8
    width: 512
    height: 512
    camera_distance_range: [0.8, 1.0]
    fovy_range: [40, 45]
    camera_perturb: 0.0
    center_perturb: 0.
    up_perturb: 0.
    elevation_range: [5, 30]
    azimuth_range: [-180, 180]
    batch_uniform_azimuth: true
    eval_camera_distance: 0.9
    eval_fovy_deg: 45.
    train_max_step: ${trainer.max_steps}
    train_val_check: ${trainer.val_check_interval}
    seed: ${seed}
    multiview_eval: true
    camera_sampling_stone: []
    cond_view: []
    relative: true

system_type: "humannorm-strand-system"
system:
  asset:
    ck_path: [
      ""
    ]
    bbox_info: [
      [1.0, 1.0, 1.0, 0.0, 0.0, 0.0]
    ]
    # scale xyz; trans xyz
    name: [
      "head"
    ]
  strand:
    bbox_info: [1.0, 1.0, 1.0, 0.0, 0.0, 0.0]
    num_strands: 3000
    sample_mode: "fixed"
    run_batch: 3000
    radius_scale: 0.5
    target_curv: 0.05
    num_edges: 4
    # straight-0.02 wavy-0.1 curly-0.2 normal-0.05
  RD:
    latent_steps: 0
  remove_img: true
  test_save_path: ???
  texture: true
  geometry_type: "tetrahedra-sdf-grid-strand"
  geometry_convert_from: ???
  geometry_convert_inherit_texture: false
  geometry:
    test_save_path: ${system.test_save_path}
    radius: 1.0 
    isosurface_resolution: 256
    isosurface_deformable_grid: true
    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.4472692374403782 # max resolution 4096
    input_type: "uvh+ori"
    n_feature_dims: 3 # albedo3 + roughness1 + metallic1 + bump3
    fix_geometry: true

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid

  # material_type: "pbr-material"
  # material:
  #   material_activation: sigmoid
  #   environment_texture: "load/lights/mud_road_puresky_1k.hdr"
  #   environment_scale: 2.0
  #   min_metallic: 0.0
  #   max_metallic: 0.0
  #   min_roughness: 0.7
  #   max_roughness: 0.9
  #   use_bump: true

  # material_type: "pbr-material-RD"
  # material:
  #   material_activation: sigmoid
  #   environment_texture: "load/lights/mud_road_puresky_4k.hdr"
  #   environment_scale: 2.0
  #   min_metallic: 0.0
  #   max_metallic: 0.9
  #   min_roughness: 0.08
  #   max_roughness: 0.9
  #   use_bump: true 

  background_type: "solid-color-background"
  background:
    n_output_dims: 3
    color: [1, 1, 1]

  renderer_type: "nvdiff-rasterizer-multiasset"
  renderer:
    use_sdf_loss: false
    context_type: cuda
    normal_type: 'camera'

  renderer_RD_type: "nvdiff-rasterizer-RD"
  renderer_RD:
    context_type: "cuda"
    camera_space: false
    mv_bg_colors: 'white'
    sd_bg_colors: 'white'

  exporter_type: "strand-mesh-exporter"
  exporter:
    fmt: "obj"
    save_flag: false

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "./pretrained_models/normal-aligned-sd1.5"
    prompt: ???
    ori_prompt: ""
    front_threshold: 45.
    back_threshold: 45.
    human_part_prompt: true

  guidance_type: "sds-du-controlnet-guidance"
  guidance:
    pretrained_model_name_or_path:  "./pretrained_models/normal-aligned-sd1.5"
    guidance_scale: 7.5
    min_step_percent: 0.02
    max_step_percent: [5000, 0.98, 0.98, 10000] # annealed to 0.5 after 5000 steps
    use_sds: true
    control_type: "input_normal"
    controlnet_name_or_path: './pretrained_models/controlnet-normal-sd1.5'
    condition_scale: 1.0
    # canny_lower_bound: 70
    # canny_upper_bound: 150

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_sds: 1.
    lambda_l1: 0.
    lambda_p: 0.
    lambda_sds_RD_StableDiffusion: 0.
    lambda_l1_RD_StableDiffusion: 0.
    lambda_p_RD_StableDiffusion: 0.
    lambda_sds_RD_Albedo: 0.
    lambda_l1_RD_Albedo: 0.
    lambda_p_RD_Albedo: 0.

  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.01
      geometry.feature_network:
        lr: 0.001
      geometry.strands_model.geo_texture_decoder:
        lr: 0
      geometry.strands_model.app_texture_decoder:
        lr: 0.001
      background:
        lr: 0.001

trainer:
  max_steps: 2000
  log_every_n_steps: 1
  num_sanity_val_steps: 120
  val_check_interval: 200
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
