name: "strand-texture-refine"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "multiview-camera-strand-datamodule"
data:
  train_downsample_resolution: 1
  eval_downsample_resolution: 1
  train_data_interval: 1
  eval_data_interval: 1
  dataroot: ???
  eval_width: 1024
  eval_height: 1024
  eval_camera_distance: 3
  eval_fovy_deg: 45.
  eval_elevation_deg: 5.
  n_views: 120

  multiview_RD:
    train_downsample_resolution: 1
    eval_downsample_resolution: 1
    train_data_interval: 1
    eval_data_interval: 1
    dataroot: ${data.dataroot}
    eval_width: 1024
    eval_height: 1024
    eval_camera_distance: 3
    eval_fovy_deg: 45.
    eval_elevation_deg: 5.
    n_views: 120

system_type: "humannorm-strand-system"
system:
  asset:
    ck_path: [
      ""
    ]
    bbox_info: [
      [1.0, 1.0, 1.0, 0.0, 0.0, 0.0]
    ]
    # scale xyz; trans xyz
    name: [
      "head"
    ]
  strand:
    bbox_info: [1.0, 1.0, 1.0, 0.0, 0.0, 0.0]
    num_strands: 3000
    sample_mode: "fixed"
    run_batch: 3000
    radius_scale: 0.5
    target_curv: 0.05
    num_edges: 4
    # straight-0.02 wavy-0.1 curly-0.2 normal-0.05
  remove_img: true
  test_save_path: ???
  texture: true
  geometry_type: "tetrahedra-sdf-grid-strand"
  geometry_convert_from: ???
  geometry_convert_inherit_texture: true
  geometry:
    test_save_path: ${system.test_save_path}
    radius: 1.0 # consistent with coarse
    isosurface_resolution: 256
    isosurface_deformable_grid: true
    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.4472692374403782 # max resolution 4096
    input_type: "uvh+ori"
    n_feature_dims: 3 # albedo3 + roughness1 + metallic1 + bump3
    fix_geometry: true

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid

  # material_type: "pbr-material"
  # material:
  #   material_activation: sigmoid
  #   environment_texture: "load/lights/mud_road_puresky_1k.hdr"
  #   environment_scale: 2.0
  #   min_metallic: 0.0
  #   max_metallic: 0.0
  #   min_roughness: 0.7
  #   max_roughness: 0.9
  #   use_bump: true

  # material_type: "pbr-material-RD"
  # material:
  #   material_activation: sigmoid
  #   environment_texture: "load/lights/mud_road_puresky_4k.hdr"
  #   environment_scale: 2.0
  #   min_metallic: 0.0
  #   max_metallic: 0.9
  #   min_roughness: 0.08
  #   max_roughness: 0.9
  #   use_bump: true # get more details

  background_type: "solid-color-background"
  background:
    n_output_dims: 3
    color: [1, 1, 1]

  renderer_type: "nvdiff-rasterizer-multiasset"
  renderer:
    use_sdf_loss: false
    context_type: cuda
    normal_type: 'camera'

  renderer_RD_type: "nvdiff-rasterizer-RD"
  renderer_RD:
    context_type: "cuda"
    camera_space: false
    mv_bg_colors: 'white'
    sd_bg_colors: 'white'

  exporter_type: "strand-mesh-exporter"
  exporter:
    fmt: "obj"
    save_flag: false

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "./pretrained_models/normal-aligned-sd1.5"
    prompt: ???
    ori_prompt: ""
    front_threshold: 45.
    back_threshold: 45.
    human_part_prompt: true

  guidance_type: "sds-du-controlnet-guidance"
  guidance:
    pretrained_model_name_or_path: "./pretrained_models/normal-aligned-sd1.5"
    min_step_percent: [5000, 0.5, 0.5, 10000]
    max_step_percent: [5000, 0.51, 0.51, 10000]
    control_type: 'input_normal'
    controlnet_name_or_path: './pretrained_models/controlnet-normal-sd1.5'
    condition_scale: 1.0
    guidance_scale: 7.5
    per_editing_step: 10
    # canny_lower_bound: 120
    # canny_upper_bound: 150

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_sds: 0.
    lambda_l1: 1.
    lambda_p: 1.
    lambda_sds_RD_StableDiffusion: 0.
    lambda_l1_RD_StableDiffusion: 0.
    lambda_p_RD_StableDiffusion: 0.
    lambda_sds_RD_Albedo: 0.
    lambda_l1_RD_Albedo: 0.
    lambda_p_RD_Albedo: 0.

  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.01
      geometry.feature_network:
        lr: 0.001
      geometry.strands_model.geo_texture_decoder:
        lr: 0
      geometry.strands_model.app_texture_decoder:
        lr: 0.001
      background:
        lr: 0.001

trainer:
  max_steps: 5000
  log_every_n_steps: 1
  num_sanity_val_steps: 120
  val_check_interval: 1000
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
